### ISSUE TITLE
Allow user to override emulator configurations

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-configgen#2]
Create a directory where configuration files can be added in order to let user override the configuration for a platforme, or even a game.

The directory structure should be like :  

```
/recalbox/share/system/customconfigs/  
```

in this directory, create the files with names corresponding to the system you want to configure :   

```
/recalbox/share/system/customconfigs/snes.cfg
```

or even the game  

```
/recalbox/share/system/customconfigs/snes/Street Fighter 2 Turbo.cfg
```

If one of those files exist, the auto generated config will be ignored, and your configuration will be loaded.

**Comment by paradadf** [comment]
This is a really good idea! Specially because of the different A <-> B and X <-> Y layouts.

Anyway, for the N64 configuration I suggest a default layout similar to this:

![mupen64plus](https://cloud.githubusercontent.com/assets/15956550/13192324/fc18bc96-d76a-11e5-8db0-89424dd52296.png)
source: https://cloud.githubusercontent.com/assets/10035308/11431965/b8207db4-9460-11e5-8b5d-45fadf9f0bfb.png

Instead of this one:

![lr-mupen](https://cloud.githubusercontent.com/assets/15956550/13192334/1112f56c-d76b-11e5-8cd5-33d961b93053.png)
source: https://cloud.githubusercontent.com/assets/10035308/7334793/6b406d8c-eb5b-11e4-8474-56a340521e71.png

The first one resembles more the original N64 Controller. But I would change the **Z** button to "L Top (L1)", **L** to "L Bottom (L2)" and **R** to "R TOP (R1)", as the L Button in N64 is practically never used and there are controllers without L2 and R2.

**Comment by substring** [comment]
I'm not sure this issue is still on our scope. But to answer @paradadf I believe the 1st mapping is the most natural, ans that's how we set it in 4.0.0.

Concernant snes type pads, thay don't have L2, R2 ok, dut don't even have analog sticks nor enough buttons for the C Pad. So in such case, once again, on 4.0.0, we got rid of the DPad and C buttons, and set Z on the X button.

**Comment by paradadf** [comment]
@substring thanks for your answer! It would be good to consider changing Z to L1 (or just L for single shoulder pads) insted of having it on the X button as it would be more natural to play, don´t you think? I never used the L button on N64, as it was "out of reach" anyway. It´s just my suggestion ;)

**Comment by substring** [comment]
@paradadf I can't say i played much N64 in my youth. I seem to remember that, most of times, L and Z were doing the same thing depending whether your wers holding the cross or the stick. If that's the case, then your idea to move Z to L1 is a good one

**Comment by paradadf** [comment]
@substring In n64 most of the games didn't use the cross at all, but the ones that did, then L and Z were assigned the same funtion. The idea is to make the n64 games as playable as possible, even with only a simpler controller without analog sticks. So I really recommend to put the Z button on the L1 trigger in controllers without L2.
I just tried an 8bitdo Zero with 4.0.0 beta 1 and Mario Kart 64 and realized that with the current configuration, the game (and many others) is unplayable. The Z funcion isn't assigned to any button at all with those controllers (in a full button controller Z is currently being assigned to L2).

**Comment by substring** [comment]
On snes type pads, Z is assigned to the recalbox X, which means Y on your 8bitdo zero

**Comment by paradadf** [comment]
Ok, I think I just found a bug. The problem shows when you connect one snes type pad and a ps3 type pad together and try to play n64. The snes pad would only have the correct configuration, if you assign it to player #1. If you assign it to #2 or don't assing at all and try to play n64 games, the buttons configuration goes mad!

**Comment by substring** [comment]
@paradadf can you make a oastebin of the ~/configs/mupen/inputautocfg.ini when you don't set any pad in es, after launching a game please ?

**Comment by paradadf** [comment]
http://pastebin.com/N604xSm3

I don't know if it is related, but when I'm on the system selection screen and the 8bitdo zero pairs with recalbox, the screen begins spinning as if left or right would be constantly being pressed.

**Comment by substring** [comment]
How many pads do you have ? 2 of them (8bitdo i guess) have almost the same name. I'm not surprised they act funny

**Comment by paradadf** [comment]
I have 4 8bitdo (2 NES30 PRO and 2 ZERO) and one usb PS3 like pad.
Not all need to be paired for the problem to occur. Even if only just one NES30 PRO and one ZERO are paired, the ZERO acts weird.

**Comment by substring** [comment]
I'm afraid that they have almost the same name, so mupen may totally miss how to map each pad :/

**Comment by paradadf** [comment]
should this be reported as an issue on recalbox os?

**Comment by substring** [comment]
concerning the original topic, https://github.com/recalbox/recalbox-configgen/pull/81 has done it for retroarch. Should we close it ? @digitalLumberjack 

For the N64 mapping, one can edit it since https://github.com/recalbox/recalbox-configgen/pull/74

**Comment by digitalLumberjack** [comment]
We can close
